import type { SiteConfig } from "@astro-minimax/core/types";

export const SITE: SiteConfig = {
  website: "http://localhost:4321/",
  author: "Demo User",
  profile: "https://github.com/",
  desc: "A demo blog built with @astro-minimax/core and @astro-minimax/viz packages.",
  title: "Minimax Demo Blog",
  ogImage: "og-image.jpg",
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showBackButton: true,
  showArchives: true,
  startDate: "2024-01-01",
  editPost: {
    enabled: false,
    text: "Edit",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr" as const,
  lang: "en",
  timezone: "UTC",
  features: {
    tags: true,
    categories: true,
    series: false,
    archives: true,
    friends: false,
    projects: false,
    search: true,
    darkMode: true,
    ai: false,
    waline: false,
    sponsor: false,
  },
  nav: {
    items: [
      { key: "home", enabled: true },
      { key: "posts", enabled: true },
      { key: "tags", enabled: true },
      { key: "categories", enabled: true },
      { key: "archives", enabled: true },
      { key: "about", enabled: true },
    ] as { key: string; enabled: boolean }[],
  },
};
